# Note: this only works if the number of concurrent jobs is >= 2
# Otherwise the codefresh run would have to run in detached mode (-d)
version: '1.0'
mode: parallel
stages:
- build

steps:
  trigger_go:
    title: Trigger codefresh-go to perform release build
    stage: build
    image: codefresh/cli
    commands:
    - codefresh run ${{CF_REPO_OWNER}}/codefresh-go/codefresh-go-build -b master
    when:
      steps:
      - name: main_clone
        on:
        - success
  trigger_python:
    title: Trigger codefresh-python to perform release build
    stage: build
    image: codefresh/cli
    commands:
    - codefresh run ${{CF_REPO_OWNER}}/codefresh-python/codefresh-python-build -b master
    when:
      steps:
      - name: main_clone
        on:
        - success
